- missing sources to respect --strict-build-id; rel 35
Changed files:
    rpm-builddir-readlink.patch -> 1.1.2.3
    rpm.spec -> 1.837.2.42.2.49.2.82

diff --git a/rpm-builddir-readlink.patch b/rpm-builddir-readlink.patch
--- a/rpm-builddir-readlink.patch
+++ b/rpm-builddir-readlink.patch
@@ -17,8 +17,8 @@
    fi
  
 +  if [ ! -s "$SOURCEFILE" ]; then
-+    echo >&2 "*** ERROR: no sources found for $f (stripped without sourcefile information?)"
-+    exit 2
++    echo >&2 "*** ${strict_error}: no sources found for $f (stripped without sourcefile information?)"
++    $strict && exit 2
 +  fi
 +
    # A binary already copied into /usr/lib/debug doesn't get stripped,
