This commit was manufactured by cvs2git to create branch 'Titanium'.
Sprout from master 2008-02-01 16:41:08 UTC Elan Ruusamäe <glen@pld-linux.org> '- revert filezilla related hack'
Cherrypick from master 2008-03-24 20:25:57 UTC Elan Ruusamäe <glen@pld-linux.org> '- add --what-provides, --what-requires':
    rpm-popt-downgrade.patch -> 1.2
Cherrypick from master 2008-11-18 13:34:55 UTC Elan Ruusamäe <glen@pld-linux.org> '- add Libraries/Java':
    rpm.groups -> 1.91
Cherrypick from master 2010-11-12 15:40:47 UTC Elan Ruusamäe <glen@pld-linux.org> '- do not output tag, wasn't needed before':
    rpm-java-requires -> 1.10
Cherrypick from rpm-4_4_9 2008-01-01 22:49:58 UTC tommat <tommat@pld-linux.org> '- updated':
    rpm-sparc64.patch -> 1.1.2.1
Cherrypick from rpm-4_4_9 2008-04-07 18:57:18 UTC Elan Ruusamäe <glen@pld-linux.org> '- jbj: fix: reverse arrows on erasure dependency graph.':
    rpm-rpm5-patchset-10061.patch -> 1.1.2.1
Delete:
    RPM-GPG-KEY
    adapter.awk
    banner.sh
    builder
    db-rpm-robustness.patch
    patch.4.5.20.1
    patch.4.5.20.2
    perl.prov
    pldnotify.awk
    rpm-bug-146549.patch
    rpm-compress-doc
    rpm-compress-doc.patch
    rpm-cpuinfo.patch
    rpm-debuginfo.patch
    rpm-dontneedutils.patch
    rpm-doxygen_hack.patch
    rpm-epoch0.patch
    rpm-error-fatal.patch
    rpm-etc_dir.patch
    rpm-find-spec-bcond
    rpm-gettext-in-header.patch
    rpm-groups-po.awk
    rpm-hack-norpmlibdep.patch
    rpm-install-tree
    rpm-javadeps.patch
    rpm-libtool-deps.patch
    rpm-lzma-size_t.patch
    rpm-macros-amd64
    rpm-macros-athlon
    rpm-macros-i386
    rpm-macros-i486
    rpm-macros-i586
    rpm-macros-i686
    rpm-macros-ia32e
    rpm-macros-noarch
    rpm-macros-pentium3
    rpm-macros-pentium4
    rpm-macros-ppc
    rpm-macros-x86_64
    rpm-macros.java
    rpm-macros.patch
    rpm-man_pl.patch
    rpm-mono.patch
    rpm-morearchs.patch
    rpm-noexpand.patch
    rpm-notsc.patch
    rpm-old-fileconflicts-behaviour.patch
    rpm-perl-macros.patch
    rpm-perl-req-perlfile.patch
    rpm-perl_req-INC_dirs.patch
    rpm-php-deps.patch
    rpm-php-macros.patch
    rpm-php-provides
    rpm-php-requires
    rpm-pkgconfigdeps.patch
    rpm-pl.po.patch
    rpm-pld-autodep.patch
    rpm-pld.macros
    rpm-po.patch
    rpm-provides-dont-obsolete.patch
    rpm-repackage-wo-lzma.patch
    rpm-rpm2cpio-payload.patch
    rpm-rpm5-patchset-8413.patch
    rpm-rpm5-patchset-8637.patch
    rpm-rpm5-patchset-8784.patch
    rpm-rpmpopt.patch
    rpm-rpmrc-resurrect.patch
    rpm-scripts-closefds.patch
    rpm-tar_as_secondary_source.patch
    rpm-truncate-cvslog.patch
    rpm-user_group.sh
    rpm-v3-support.patch
    rpm.macros
    rpm.platform
    rpm.spec
    rpm.sysconfig
    rpm.sysinfo

diff --git a/rpm-java-requires b/rpm-java-requires
--- a/rpm-java-requires
+++ b/rpm-java-requires
@@ -7,44 +7,96 @@
 
 export PATH="/sbin:/usr/sbin:/bin:/usr/bin"
 
-javaclassversion() {
-	[ $# -gt 0 ] || return
+# Enable debug: JAVADEPS_DEBUG=true
+: ${JAVADEPS_DEBUG=false}
 
-	local ver
-	classver=$(echo "$@" | xargs -r file | grep -o 'compiled Java class data, version [0-9.]*' | awk '{print $NF}' | sort -u)
-	[ "$classver" ] || return
+# save $- state, to enable in functions
+debug=$-
+
+javaclassversion() {
+	set -$debug
+	local mode=$1; shift
+	[ $# -gt 0 ] || return 1
+	$JAVADEPS_DEBUG && echo >&2 ">> javaclassversion($mode): $*"
+
+	# process only requires
+	[ "$mode" = requires ] || return $ret
+
+	local classver=$(echo "$@" | xargs -r file | grep -o 'compiled Java class data, version [0-9.]*' | awk '{print $NF}' | sort -u)
+	if [ -z "$classver" ]; then
+		return 1
+	fi
+
+	local v
 	for v in $classver; do
 		echo "java(ClassDataVersion) >= $v"
 	done
+	return 0
 }
 
 javajarversion() {
-	local jar="$1"
+	set -$debug
+	local mode=$1; shift
+	local jar=$1
+	local tmp ret=0
+	$JAVADEPS_DEBUG && echo >&2 ">> javajarversion($mode): $jar"
 
 	# check only files, symlinks could point outside buildroot
-	[ -f "$jar" -a ! -L "$jar" ] || return
-
-#	echo >&2 "find java requires: ${jar#$RPM_BUILD_ROOT}"
+	[ -f "$jar" -a ! -L "$jar" ] || return $ret
 
 	tmp=$(mktemp -d)
 	unzip -q -d $tmp $jar >&2
-	javaclassversion $(find $tmp -type f -name '*.class')
+	# workaround for .jar files with stupid permissions
+	chmod -R u+rwX $tmp
+
+	# find .jar and .class files
+	find_javadeps $mode $(find $tmp -type f -regextype posix-extended  -regex '^.+\.(class|jar)$') || ret=1
 	rm -rf $tmp
+	return $ret
 }
 
-FILES=$(cat -)
+find_javadeps() {
+	set -$debug
+	local mode=$1; shift
+	local ret=0
 
-find_requires() {
-	for file in $FILES; do
+	$JAVADEPS_DEBUG && echo >&2 ">> find_javadeps($mode): $*"
+	for file in $@; do
 		case $file in
 		*.jar)
-			javajarversion "$file"
+			javajarversion $mode "$file" || ret=1
 		;;
 		*.class)
-			javaclassversion "$file"
+			javaclassversion $mode "$file" || {
+				echo >&2 "ERROR: Class version could not be extracted from $file"
+				ret=1
+			}
+		;;
+		*)
+			$JAVADEPS_DEBUG && echo >&2 ">> find_javadeps($mode): no handle: $file"
 		;;
 		esac
 	done
+	return $ret
 }
 
-find_requires | sort -u
+ret=0
+# default mode to requires for backward compat
+mode=requires
+case $1 in
+-P|--provides)
+	mode=provides
+	shift
+	;;
+-R|--requires)
+	mode=requires
+	shift
+	;;
+esac
+
+t=$(mktemp)
+find_javadeps $mode $(cat -) > $t || ret=1
+sort -u $t
+rm -f $t
+
+exit $ret
